# This is a basic workflow to help you get started with Actions

name: CI for C#

# Controls when the action will run. Triggers the workflow on creation of a release
# 
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        build-target: ['production','demo','sales']    

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v1.0.1        
        echo "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/" >> $GITHUB_PATH
        
      - name: Build
        run: MSBuild.exe /p:DeployOnBuild=true /p:Configuration=Release /p:PublishProfile=${{matrix.build-target}}
        shell: pwsh

      - name: create sales archive
        run: |
               Compress-Archive -Path app.publish\* -DestinationPath ${{matrix.build-target}}-api.zip
        shell: pwsh

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{matrix.build-target}}-api.zip
          asset_name: ${{matrix.build-target}}-api.zip
          asset_content_type: application/zip          
